### ISSUE TITLE
Parametrized fixture regression in branch fixture-stack

### ISSUE THREAD

**Issue by oakkitten** [blueyed/pytest#365]
as reported [here](https://github.com/pytest-dev/pytest/issues/7053#issuecomment-638551342) and confirmed by my tests, branch `fixture-stack` runs a parametrized fixture a suboptimal amount of times.

running [this example](https://repl.it/@oakkitten/RightSomberDatabases), output using current upstream master (5.4.1.dev422+gcf640a9b6, also 3.10.1 and some versions in between):
```
test_cats_dogs.py dog charlie
cat tom
.sssdog buddy
ss.scat simba
sss.dog charlie
s.ss
```

output from `fixtue-stack`:

```
test_cats_dogs.py dog charlie
cat tom
.sssdog buddy
cat tom
ss.scat simba
sss.dog charlie
cat simba
s.ss
```

**Comment by blueyed** [comment]
Thanks for the report.  Should go into the discussion on/of the PR itself though: https://github.com/pytest-dev/pytest/pull/6551.

(FYI: I do not plan to finish/work on this myself anytime soon in the pytest-dev/pytest project itself.)

**Comment by SalmonMode** [comment]
@blueyed as discussed on https://github.com/pytest-dev/pytest/issues/7053, that is not a problem with the `fixture-stack` branch. That was a misunderstanding of the description of how pytest "optimizes" the fixtures it runs. I will remake the branch and take over the work again though.
